### ISSUE TITLE
Is the c++ implementation of R7PF ready to use?

### ISSUE THREAD

**Issue by simonlynen** [CenekAlbl/RnP#2]
The readme in the repo suggests it isn't ready; but some recent commits sound like it's working already. Thanks!

**Comment by CenekAlbl** [comment]
Hi, some core parts are working already, but the whole thing is not ready
yet. I am too busy right now but I expect to finish in September. Would you
like to try it earlier?

st 26. 8. 2020 v 17:16 odesílatel Simon Lynen <notifications@github.com>
napsal:

**Comment by simonlynen** [comment]
No rush; I was just curious given that the paper has results showing good gains over p4pf+r which we evaluated earlier and I'd love to try the r7pf solver out in our system as well to benchmark it against other solutions we have.

Please just drop me a note when you think we can give it a try :) Thanks

**Comment by CenekAlbl** [comment]
The implementation in C++ of all algorithms including r7pf and r7pfr is now ready. Python bindings also available, MATLAB coming.
